pipeline {
    agent any
    options {
        copyArtifactPermission('Deply application to staging environment');
    }
    tools { 
        maven 'Localmaven' 
        jdk 'LocaljDK17' 
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'Deply application to staging environment'

            }
            
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'deploy application prod environment'
            }
        }
    }
}
